---
- name: Setup laptop
  hosts: localhost
  become: true
  gather_facts: false
  vars_files:
  - vars/vars.yml
  tasks:
    - name: Install and Upgrade packages
      block:

      - name: Upgrade all packages
        ansible.builtin.dnf:
          name: "*"
          use_backend: dnf
          state: latest

      - name: Enable VSCode repository
        ansible.builtin.yum_repository:
          name: "{{ vscode['name'] }}"
          description: "{{ vscode['description'] }}"
          baseurl: "{{ vscode['baseurl'] }}"
          gpgkey: "{{ vscode['gpgkey'] }}"

      - name: Install packages
        ansible.builtin.dnf:
          name: "{{ packages }}"
          use_backend: dnf
          state: latest

      - name: Install Google Chrome
        ansible.builtin.dnf:
          name: "{{ chrome }}"
          disable_gpg_check: true
          state: present
      
      rescue:
        - name: Failed to install or upgrade packages
          ansible.builtin.debug:
            msg: Failed to install or upgrade packages

    - name: Configure vim editor
      ansible.builtin.template:
        src: templates/vimrc.j2
        dest: ~/.vimrc
      become: false

    - name: Install and configure Apache Maven
      block:
      - name: Download maven tarball
        ansible.builtin.get_url:
          url: "{{ maven['url'] }}"
          dest: "{{ maven['temp_destination'] }}"

      - name: Create maven home
        ansible.builtin.file:
          path: "{{ maven['destination'] }}"
          state: directory

      - name: Untar maven
        ansible.builtin.unarchive:
          src: "{{ maven['temp_destination'] }}"
          dest: /opt/

      - name: Set Maven Home
        ansible.builtin.blockinfile:
          path: /etc/profile.d/maven.sh
          create: true
          state: present
          mode: '0744'
          block: |
            export M2_HOME={{ maven['destination'] }}
            export MAVEN_HOME={{ maven['destination'] }}
            export PATH=${M2_HOME}/bin:${PATH}

      rescue:
        - name: Failed to install and configure Apache Maven
          ansible.builtin.debug:
            msg: Failed to install and configure Apache Maven

    - name: Install and configure Gradle
      block:
      - name: Download gradle zip
        ansible.builtin.get_url:
          url: "{{ gradle['url'] }}"
          dest: "{{ gradle['temp_destination'] }}"

      - name: Create Gradle home
        ansible.builtin.file:
          path: "{{ gradle['destination'] }}"
          state: directory

      - name: Unzip Gradle
        ansible.builtin.unarchive:
          src: "{{ gradle['temp_destination'] }}"
          dest: /opt/

      - name: Set Gradle Home
        ansible.builtin.blockinfile:
          path: /etc/profile.d/gradle.sh
          create: true
          state: present
          mode: '0744'
          block: |
            export PATH={{ gradle['destination'] }}/bin:${PATH}

      rescue:
        - name: Failed to install and configure Gradle
          ansible.builtin.debug:
            msg: Failed to install and configure Gradle
